### ISSUE TITLE
ERROR with "/tagslam/path/body_rig"

### ISSUE THREAD

**Issue by ThinkPig826** [berndpfrommer/tagslam#30]
![Screenshot from 2022-05-17 15-14-29](https://user-images.githubusercontent.com/35769172/168751810-800322a4-f0cd-498a-aef4-563e49f29272.png)
I just started using this program, why am I getting the path like this.

**Comment by berndpfrommer** [comment]
To properly diagnose this you need to provide more information.
The first thing to look at is the intrinsic camera calibration. How was that one done, what is the reprojection error, was it entered correctly?
Also I can see a calibration board in the picture. Could be that the tag detector occasionally decodes those tags, and that the tag numbers collide with the tags you have on the wall (16, 17).
Lastly, you are quite far away from the tags, and there are only two of them, fairly close together. You won't get a very good pose estimate (although it should be much better than what you are getting).

**Comment by ThinkPig826** [comment]
Thank you very much for your reply!
   I increased the number of tags, reduced the distance between the camera and the tag,  the positioning effect was significantly improved.
![Screenshot from 2022-05-18 17-17-05](https://user-images.githubusercontent.com/35769172/169005437-5f352b50-7b45-4a33-a32d-f65b3408a095.png)

In addition, I feel that the system is relatively stuck when running. Do you have a good method?
Finally, thanks again for your reply

**Comment by berndpfrommer** [comment]
Not sure what you mean with "relatively stuck".
- if you get no pose updates for a while, it is most likely because no tags are detected. A common reason for that is that no tags are in view (duh) or that the detector fails to detect due to motion blur. Use larger tags, more tags, and *better lighting*.
- if Tagslam bogs down (computes a long time) you can do this: first map out all the tags. Then cut-and-paste the tag poses (look in ~/.ros for the output) into your tagslam.yaml file. Then set "amnesia" to "true" in tagslam.yaml (see instructions). Now tagslam should no longer bog down.

**Comment by ThinkPig826** [comment]
ok，thanks！
